/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/Control'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Control'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.CheckSummaryOfTheSubmittedDocument = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.Control);
  }
}(this, function(ApiClient, Control) {
  'use strict';




  /**
   * The CheckSummaryOfTheSubmittedDocument model module.
   * @module invoker/model/CheckSummaryOfTheSubmittedDocument
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CheckSummaryOfTheSubmittedDocument</code>.
   * @alias module:invoker/model/CheckSummaryOfTheSubmittedDocument
   * @class
   * @param check {Array.<module:invoker/model/Control>} check results
   */
  var exports = function(check) {
    var _this = this;

    _this['check'] = check;
  };

  /**
   * Constructs a <code>CheckSummaryOfTheSubmittedDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/CheckSummaryOfTheSubmittedDocument} obj Optional instance to populate.
   * @return {module:invoker/model/CheckSummaryOfTheSubmittedDocument} The populated <code>CheckSummaryOfTheSubmittedDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('check')) {
        obj['check'] = ApiClient.convertToType(data['check'], [Control]);
      }
    }
    return obj;
  }

  /**
   * check results
   * @member {Array.<module:invoker/model/Control>} check
   */
  exports.prototype['check'] = undefined;



  return exports;
}));


