/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.ClassificationOfTheSubmittedDocument = factory(root.idcheckio_nodejs_client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClassificationOfTheSubmittedDocument model module.
   * @module invoker/model/ClassificationOfTheSubmittedDocument
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ClassificationOfTheSubmittedDocument</code>.
   * @alias module:invoker/model/ClassificationOfTheSubmittedDocument
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ClassificationOfTheSubmittedDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/ClassificationOfTheSubmittedDocument} obj Optional instance to populate.
   * @return {module:invoker/model/ClassificationOfTheSubmittedDocument} The populated <code>ClassificationOfTheSubmittedDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('idType')) {
        obj['idType'] = ApiClient.convertToType(data['idType'], 'String');
      }
    }
    return obj;
  }

  /**
   * identity document type
   * @member {module:invoker/model/ClassificationOfTheSubmittedDocument.IdTypeEnum} idType
   */
  exports.prototype['idType'] = undefined;


  /**
   * Allowed values for the <code>idType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IdTypeEnum = {
    /**
     * value: "ID"
     * @const
     */
    "ID": "ID",
    /**
     * value: "P"
     * @const
     */
    "P": "P",
    /**
     * value: "RP"
     * @const
     */
    "RP": "RP",
    /**
     * value: "V"
     * @const
     */
    "V": "V",
    /**
     * value: "DL"
     * @const
     */
    "DL": "DL",
    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"  };


  return exports;
}));


