/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/EventDate', 'invoker/model/GenericData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventDate'), require('./GenericData'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.DetailedInformationOfTheSubmittedDocument = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.EventDate, root.idcheckio_nodejs_client.GenericData);
  }
}(this, function(ApiClient, EventDate, GenericData) {
  'use strict';




  /**
   * The DetailedInformationOfTheSubmittedDocument model module.
   * @module invoker/model/DetailedInformationOfTheSubmittedDocument
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DetailedInformationOfTheSubmittedDocument</code>.
   * @alias module:invoker/model/DetailedInformationOfTheSubmittedDocument
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>DetailedInformationOfTheSubmittedDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/DetailedInformationOfTheSubmittedDocument} obj Optional instance to populate.
   * @return {module:invoker/model/DetailedInformationOfTheSubmittedDocument} The populated <code>DetailedInformationOfTheSubmittedDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('emitCountry')) {
        obj['emitCountry'] = ApiClient.convertToType(data['emitCountry'], 'String');
      }
      if (data.hasOwnProperty('emitDate')) {
        obj['emitDate'] = EventDate.constructFromObject(data['emitDate']);
      }
      if (data.hasOwnProperty('expirationDate')) {
        obj['expirationDate'] = EventDate.constructFromObject(data['expirationDate']);
      }
      if (data.hasOwnProperty('documentNumber')) {
        obj['documentNumber'] = ApiClient.convertToType(data['documentNumber'], 'String');
      }
      if (data.hasOwnProperty('extraInfos')) {
        obj['extraInfos'] = ApiClient.convertToType(data['extraInfos'], [GenericData]);
      }
    }
    return obj;
  }

  /**
   * emit country
   * @member {String} emitCountry
   */
  exports.prototype['emitCountry'] = undefined;
  /**
   * @member {module:invoker/model/EventDate} emitDate
   */
  exports.prototype['emitDate'] = undefined;
  /**
   * @member {module:invoker/model/EventDate} expirationDate
   */
  exports.prototype['expirationDate'] = undefined;
  /**
   * document number
   * @member {String} documentNumber
   */
  exports.prototype['documentNumber'] = undefined;
  /**
   * additional informations
   * @member {Array.<module:invoker/model/GenericData>} extraInfos
   */
  exports.prototype['extraInfos'] = undefined;



  return exports;
}));


