/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/EventDate', 'invoker/model/GenericData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventDate'), require('./GenericData'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.DetailedInformationOfTheHolderOfTheSubmittedDocument = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.EventDate, root.idcheckio_nodejs_client.GenericData);
  }
}(this, function(ApiClient, EventDate, GenericData) {
  'use strict';




  /**
   * The DetailedInformationOfTheHolderOfTheSubmittedDocument model module.
   * @module invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DetailedInformationOfTheHolderOfTheSubmittedDocument</code>.
   * @alias module:invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>DetailedInformationOfTheHolderOfTheSubmittedDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument} obj Optional instance to populate.
   * @return {module:invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument} The populated <code>DetailedInformationOfTheHolderOfTheSubmittedDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = ApiClient.convertToType(data['lastName'], ['String']);
      }
      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = ApiClient.convertToType(data['firstName'], ['String']);
      }
      if (data.hasOwnProperty('usageName')) {
        obj['usageName'] = ApiClient.convertToType(data['usageName'], 'String');
      }
      if (data.hasOwnProperty('nationality')) {
        obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('birthDate')) {
        obj['birthDate'] = EventDate.constructFromObject(data['birthDate']);
      }
      if (data.hasOwnProperty('birthPlace')) {
        obj['birthPlace'] = ApiClient.convertToType(data['birthPlace'], 'String');
      }
      if (data.hasOwnProperty('birthDpt')) {
        obj['birthDpt'] = ApiClient.convertToType(data['birthDpt'], 'String');
      }
      if (data.hasOwnProperty('extraInfos')) {
        obj['extraInfos'] = ApiClient.convertToType(data['extraInfos'], [GenericData]);
      }
    }
    return obj;
  }

  /**
   * list of lastnames
   * @member {Array.<String>} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * list of firstnames
   * @member {Array.<String>} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * usage name
   * @member {String} usageName
   */
  exports.prototype['usageName'] = undefined;
  /**
   * nationality
   * @member {String} nationality
   */
  exports.prototype['nationality'] = undefined;
  /**
   * gender
   * @member {String} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * address
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {module:invoker/model/EventDate} birthDate
   */
  exports.prototype['birthDate'] = undefined;
  /**
   * birth place
   * @member {String} birthPlace
   */
  exports.prototype['birthPlace'] = undefined;
  /**
   * birth department
   * @member {String} birthDpt
   */
  exports.prototype['birthDpt'] = undefined;
  /**
   * additional information
   * @member {Array.<module:invoker/model/GenericData>} extraInfos
   */
  exports.prototype['extraInfos'] = undefined;



  return exports;
}));


