/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/ImageIndicator'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageIndicator'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.ExtractedImage = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.ImageIndicator);
  }
}(this, function(ApiClient, ImageIndicator) {
  'use strict';




  /**
   * The ExtractedImage model module.
   * @module invoker/model/ExtractedImage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ExtractedImage</code>.
   * @alias module:invoker/model/ExtractedImage
   * @class
   * @param type {module:invoker/model/ExtractedImage.TypeEnum} 
   */
  var exports = function(type) {
    var _this = this;

    _this['type'] = type;





  };

  /**
   * Constructs a <code>ExtractedImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/ExtractedImage} obj Optional instance to populate.
   * @return {module:invoker/model/ExtractedImage} The populated <code>ExtractedImage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('imageDL')) {
        obj['imageDL'] = ApiClient.convertToType(data['imageDL'], ['String']);
      }
      if (data.hasOwnProperty('imageIR')) {
        obj['imageIR'] = ApiClient.convertToType(data['imageIR'], ['String']);
      }
      if (data.hasOwnProperty('imageUV')) {
        obj['imageUV'] = ApiClient.convertToType(data['imageUV'], ['String']);
      }
      if (data.hasOwnProperty('page')) {
        obj['page'] = ApiClient.convertToType(data['page'], 'Integer');
      }
      if (data.hasOwnProperty('indicators')) {
        obj['indicators'] = ApiClient.convertToType(data['indicators'], [ImageIndicator]);
      }
    }
    return obj;
  }

  /**
   * @member {module:invoker/model/ExtractedImage.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Array.<String>} imageDL
   */
  exports.prototype['imageDL'] = undefined;
  /**
   * @member {Array.<String>} imageIR
   */
  exports.prototype['imageIR'] = undefined;
  /**
   * @member {Array.<String>} imageUV
   */
  exports.prototype['imageUV'] = undefined;
  /**
   * @member {Integer} page
   */
  exports.prototype['page'] = undefined;
  /**
   * @member {Array.<module:invoker/model/ImageIndicator>} indicators
   */
  exports.prototype['indicators'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "CROPPED_RECTO"
     * @const
     */
    "RECTO": "CROPPED_RECTO",
    /**
     * value: "CROPPED_VERSO"
     * @const
     */
    "VERSO": "CROPPED_VERSO",
    /**
     * value: "CROPPED_FACE"
     * @const
     */
    "FACE": "CROPPED_FACE",
    /**
     * value: "CROPPED_SIGNATURE"
     * @const
     */
    "SIGNATURE": "CROPPED_SIGNATURE",
    /**
     * value: "CROPPED_EMITTER_SIGNATURE"
     * @const
     */
    "EMITTER_SIGNATURE": "CROPPED_EMITTER_SIGNATURE"  };


  return exports;
}));


