/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/CheckSummaryOfTheSubmittedDocument', 'invoker/model/ClassificationOfTheSubmittedDocument', 'invoker/model/ControlGroup', 'invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument', 'invoker/model/DetailedInformationOfTheSubmittedDocument', 'invoker/model/ExtractedImage', 'invoker/model/Mrz'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CheckSummaryOfTheSubmittedDocument'), require('./ClassificationOfTheSubmittedDocument'), require('./ControlGroup'), require('./DetailedInformationOfTheHolderOfTheSubmittedDocument'), require('./DetailedInformationOfTheSubmittedDocument'), require('./ExtractedImage'), require('./Mrz'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.ResultResponse = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.CheckSummaryOfTheSubmittedDocument, root.idcheckio_nodejs_client.ClassificationOfTheSubmittedDocument, root.idcheckio_nodejs_client.ControlGroup, root.idcheckio_nodejs_client.DetailedInformationOfTheHolderOfTheSubmittedDocument, root.idcheckio_nodejs_client.DetailedInformationOfTheSubmittedDocument, root.idcheckio_nodejs_client.ExtractedImage, root.idcheckio_nodejs_client.Mrz);
  }
}(this, function(ApiClient, CheckSummaryOfTheSubmittedDocument, ClassificationOfTheSubmittedDocument, ControlGroup, DetailedInformationOfTheHolderOfTheSubmittedDocument, DetailedInformationOfTheSubmittedDocument, ExtractedImage, Mrz) {
  'use strict';




  /**
   * The ResultResponse model module.
   * @module invoker/model/ResultResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResultResponse</code>.
   * @alias module:invoker/model/ResultResponse
   * @class
   * @param uid {String} uid
   * @param analysisRefUid {String} analysisRefUid
   * @param checkReportSummary {module:invoker/model/CheckSummaryOfTheSubmittedDocument} 
   * @param documentClassification {module:invoker/model/ClassificationOfTheSubmittedDocument} 
   * @param documentDetail {module:invoker/model/DetailedInformationOfTheSubmittedDocument} 
   * @param holderDetail {module:invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument} 
   * @param mrz {module:invoker/model/Mrz} 
   * @param controls {Array.<module:invoker/model/ControlGroup>} Performed controls on the submitted document
   */
  var exports = function(uid, analysisRefUid, checkReportSummary, documentClassification, documentDetail, holderDetail, mrz, controls) {
    var _this = this;

    _this['uid'] = uid;
    _this['analysisRefUid'] = analysisRefUid;
    _this['checkReportSummary'] = checkReportSummary;
    _this['documentClassification'] = documentClassification;
    _this['documentDetail'] = documentDetail;
    _this['holderDetail'] = holderDetail;
    _this['mrz'] = mrz;
    _this['controls'] = controls;

  };

  /**
   * Constructs a <code>ResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/ResultResponse} obj Optional instance to populate.
   * @return {module:invoker/model/ResultResponse} The populated <code>ResultResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('analysisRefUid')) {
        obj['analysisRefUid'] = ApiClient.convertToType(data['analysisRefUid'], 'String');
      }
      if (data.hasOwnProperty('checkReportSummary')) {
        obj['checkReportSummary'] = CheckSummaryOfTheSubmittedDocument.constructFromObject(data['checkReportSummary']);
      }
      if (data.hasOwnProperty('documentClassification')) {
        obj['documentClassification'] = ClassificationOfTheSubmittedDocument.constructFromObject(data['documentClassification']);
      }
      if (data.hasOwnProperty('documentDetail')) {
        obj['documentDetail'] = DetailedInformationOfTheSubmittedDocument.constructFromObject(data['documentDetail']);
      }
      if (data.hasOwnProperty('holderDetail')) {
        obj['holderDetail'] = DetailedInformationOfTheHolderOfTheSubmittedDocument.constructFromObject(data['holderDetail']);
      }
      if (data.hasOwnProperty('mrz')) {
        obj['mrz'] = Mrz.constructFromObject(data['mrz']);
      }
      if (data.hasOwnProperty('controls')) {
        obj['controls'] = ApiClient.convertToType(data['controls'], [ControlGroup]);
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], [ExtractedImage]);
      }
    }
    return obj;
  }

  /**
   * uid
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * analysisRefUid
   * @member {String} analysisRefUid
   */
  exports.prototype['analysisRefUid'] = undefined;
  /**
   * @member {module:invoker/model/CheckSummaryOfTheSubmittedDocument} checkReportSummary
   */
  exports.prototype['checkReportSummary'] = undefined;
  /**
   * @member {module:invoker/model/ClassificationOfTheSubmittedDocument} documentClassification
   */
  exports.prototype['documentClassification'] = undefined;
  /**
   * @member {module:invoker/model/DetailedInformationOfTheSubmittedDocument} documentDetail
   */
  exports.prototype['documentDetail'] = undefined;
  /**
   * @member {module:invoker/model/DetailedInformationOfTheHolderOfTheSubmittedDocument} holderDetail
   */
  exports.prototype['holderDetail'] = undefined;
  /**
   * @member {module:invoker/model/Mrz} mrz
   */
  exports.prototype['mrz'] = undefined;
  /**
   * Performed controls on the submitted document
   * @member {Array.<module:invoker/model/ControlGroup>} controls
   */
  exports.prototype['controls'] = undefined;
  /**
   * Cropped image of the submitted document according request
   * @member {Array.<module:invoker/model/ExtractedImage>} image
   */
  exports.prototype['image'] = undefined;



  return exports;
}));


