/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.TaskResponse = factory(root.idcheckio_nodejs_client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TaskResponse model module.
   * @module invoker/model/TaskResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TaskResponse</code>.
   * @alias module:invoker/model/TaskResponse
   * @class
   * @param uid {String} analysisRefUid
   */
  var exports = function(uid) {
    var _this = this;

    _this['uid'] = uid;








  };

  /**
   * Constructs a <code>TaskResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/TaskResponse} obj Optional instance to populate.
   * @return {module:invoker/model/TaskResponse} The populated <code>TaskResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('isWithProgress')) {
        obj['isWithProgress'] = ApiClient.convertToType(data['isWithProgress'], 'Boolean');
      }
      if (data.hasOwnProperty('accepted')) {
        obj['accepted'] = ApiClient.convertToType(data['accepted'], 'Integer');
      }
      if (data.hasOwnProperty('started')) {
        obj['started'] = ApiClient.convertToType(data['started'], 'Integer');
      }
      if (data.hasOwnProperty('ended')) {
        obj['ended'] = ApiClient.convertToType(data['ended'], 'Integer');
      }
      if (data.hasOwnProperty('lastProgress')) {
        obj['lastProgress'] = ApiClient.convertToType(data['lastProgress'], 'Integer');
      }
      if (data.hasOwnProperty('percentage')) {
        obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Integer');
      }
      if (data.hasOwnProperty('redirectUrl')) {
        obj['redirectUrl'] = ApiClient.convertToType(data['redirectUrl'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * analysisRefUid
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * task with progress
   * @member {Boolean} isWithProgress
   * @default false
   */
  exports.prototype['isWithProgress'] = false;
  /**
   * task accepted date
   * @member {Integer} accepted
   */
  exports.prototype['accepted'] = undefined;
  /**
   * task started date
   * @member {Integer} started
   */
  exports.prototype['started'] = undefined;
  /**
   * task ended date
   * @member {Integer} ended
   */
  exports.prototype['ended'] = undefined;
  /**
   * last progress date
   * @member {Integer} lastProgress
   */
  exports.prototype['lastProgress'] = undefined;
  /**
   * percentage progress
   * @member {Integer} percentage
   */
  exports.prototype['percentage'] = undefined;
  /**
   * redirect url
   * @member {String} redirectUrl
   */
  exports.prototype['redirectUrl'] = undefined;
  /**
   * message
   * @member {String} message
   */
  exports.prototype['message'] = undefined;



  return exports;
}));


