/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/ErrorResponse', 'invoker/model/ImageListResponse', 'invoker/model/MrzResponse', 'invoker/model/MrzListResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/ImageListResponse'), require('../model/MrzResponse'), require('../model/MrzListResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.idcheckio_nodejs_client) {
      root.idcheckio_nodejs_client = {};
    }
    root.idcheckio_nodejs_client.SandboxApi = factory(root.idcheckio_nodejs_client.ApiClient, root.idcheckio_nodejs_client.ErrorResponse, root.idcheckio_nodejs_client.ImageListResponse, root.idcheckio_nodejs_client.MrzResponse, root.idcheckio_nodejs_client.MrzListResponse);
  }
}(this, function(ApiClient, ErrorResponse, ImageListResponse, MrzResponse, MrzListResponse) {
  'use strict';

  /**
   * Sandbox service.
   * @module invoker/api/SandboxApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SandboxApi. 
   * @alias module:invoker/api/SandboxApi
   * @class
   * @param {module:invoker/ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:invoker/ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getImage operation.
     * @callback module:invoker/api/SandboxApi~getImageCallback
     * @param {String} error Error message, if any.
     * @param {Array.<'String'>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HTTP GET image
     * GET image
     * @param {String} imageUid EnumDemoDocsImage
     * @param {Object} opts Optional parameters
     * @param {module:invoker/model/String} opts.rawType Image raw type
     * @param {module:invoker/model/String} opts.face Image face
     * @param {module:invoker/model/String} opts.light Image light
     * @param {module:invoker/api/SandboxApi~getImageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<'String'>}
     */
    this.getImage = function(imageUid, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'imageUid' is set
      if (imageUid == undefined || imageUid == null) {
        throw "Missing the required parameter 'imageUid' when calling getImage";
      }


      var pathParams = {
        'imageUid': imageUid
      };
      var queryParams = {
        'rawType': opts['rawType'],
        'face': opts['face'],
        'light': opts['light']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*_/_*'];
      var returnType = ['String'];

      return this.apiClient.callApi(
        '/v0/sandbox/image/{imageUid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getImageList operation.
     * @callback module:invoker/api/SandboxApi~getImageListCallback
     * @param {String} error Error message, if any.
     * @param {module:invoker/model/ImageListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HTTP GET images list
     * GET images list
     * @param {module:invoker/api/SandboxApi~getImageListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:invoker/model/ImageListResponse}
     */
    this.getImageList = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = ImageListResponse;

      return this.apiClient.callApi(
        '/v0/sandbox/imagelist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMrz operation.
     * @callback module:invoker/api/SandboxApi~getMrzCallback
     * @param {String} error Error message, if any.
     * @param {module:invoker/model/MrzResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HTTP GET mrz
     * GET mrz
     * @param {String} mrzUid EnumDemoDocsMrz
     * @param {module:invoker/api/SandboxApi~getMrzCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:invoker/model/MrzResponse}
     */
    this.getMrz = function(mrzUid, callback) {
      var postBody = null;

      // verify the required parameter 'mrzUid' is set
      if (mrzUid == undefined || mrzUid == null) {
        throw "Missing the required parameter 'mrzUid' when calling getMrz";
      }


      var pathParams = {
        'mrzUid': mrzUid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = MrzResponse;

      return this.apiClient.callApi(
        '/v0/sandbox/mrz/{mrzUid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMrzList operation.
     * @callback module:invoker/api/SandboxApi~getMrzListCallback
     * @param {String} error Error message, if any.
     * @param {module:invoker/model/MrzListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HTTP GET mrz list
     * GET mrz list
     * @param {module:invoker/api/SandboxApi~getMrzListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:invoker/model/MrzListResponse}
     */
    this.getMrzList = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json; charset=utf-8'];
      var returnType = MrzListResponse;

      return this.apiClient.callApi(
        '/v0/sandbox/mrzlist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
