/**
 * IdCheck.IO API
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/invoker/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/invoker/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.idcheckio_nodejs_client);
  }
}(this, function(expect, idcheckio_nodejs_client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new idcheckio_nodejs_client.ImageRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImageRequest', function() {
    it('should create an instance of ImageRequest', function() {
      // uncomment below and update the code to test ImageRequest
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be.a(idcheckio_nodejs_client.ImageRequest);
    });

    it('should have the property apiVersion (base name: "apiVersion")', function() {
      // uncomment below and update the code to test the property apiVersion
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property frontImage (base name: "frontImage")', function() {
      // uncomment below and update the code to test the property frontImage
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property frontImageIr (base name: "frontImageIr")', function() {
      // uncomment below and update the code to test the property frontImageIr
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property frontImageUv (base name: "frontImageUv")', function() {
      // uncomment below and update the code to test the property frontImageUv
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property backImage (base name: "backImage")', function() {
      // uncomment below and update the code to test the property backImage
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property backImageIr (base name: "backImageIr")', function() {
      // uncomment below and update the code to test the property backImageIr
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property backImageUv (base name: "backImageUv")', function() {
      // uncomment below and update the code to test the property backImageUv
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property rectoImageCropped (base name: "rectoImageCropped")', function() {
      // uncomment below and update the code to test the property rectoImageCropped
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property faceImageCropped (base name: "faceImageCropped")', function() {
      // uncomment below and update the code to test the property faceImageCropped
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageCropped (base name: "signatureImageCropped")', function() {
      // uncomment below and update the code to test the property signatureImageCropped
      //var instane = new idcheckio_nodejs_client.ImageRequest();
      //expect(instance).to.be();
    });

  });

}));
